In [1]:
# Basic Syntax - IF

# if (condition){
    #Execute some code
# }

In [2]:
hot <- FALSE
temp <- 60

In [3]:
if (temp > 80){
    hot = TRUE
    }
hot

[1] FALSE

In [4]:
temp <- 100

if (temp > 80){
    hot <- TRUE
    }
hot

[1] TRUE

In [5]:
if (1 == 1){
    print('Hello')
}

[1] "Hello"


In [ ]:
# Basic Syntax - ELSE

# if (condition){
    #Execute some code
# }else{
    #Additional code
#}

In [6]:
temp <- 75

if (temp > 95){
    print('Too hot to pick peanuts')
}else{print('Not a bad day for combining!')
     }

[1] "Not a bad day for combining!"


In [ ]:
# Basic Syntax - ELSE IF

# if (condition){
    #Execute some code
# } esle if (condition){
    #Execute more code
# } else{
    #Additional code
# }

In [8]:
temp <- 45

if (temp > 80){
    print('Too hot to pick peanuts')
} else if (temp <80 & temp >50){
    print('Perfect combining weather')
} else if (temp < 50 & temp > 32){
    print('Are we in Michigan')
}else{print('Global Warming is fake')
     }

[1] "Are we in Michigan"


In [9]:
# Multiple Conditions using if, else if, else

line <- "N14023"
yield <- 5800
leaf_spot <- 2.5

report <- 'Blank'

if (yield >= 550 & leaf_spot <= 3){
    report <- paste('Release',line)
} else if (yield >=5500 & leaf_spot > 3){
    report<-paste(line,"is a good agronomic parent")
} else if (yield <=5500 & leaf_spot <= 3){
    report<-paste(line,"is a good disease resistant parent")
} else{
    report<- paste ('Drop',line)
}
report

[1] "Release N14023"

In [11]:
# Working with DATAFRAMES

lines <- c('Bailey',"Bailey II","Sullivan","Emery")
yield <- c(5100,5600,5200,4900)
peanuts <- data.frame(lines,yield)
peanuts

lines     yield
1 Bailey    5100 
2 Bailey II 5600 
3 Sullivan  5200 
4 Emery     4900

In [20]:
test <- min(peanuts$yield)

if (peanuts$yield[1]== test){
    print(paste(peanut$lines[1],'has the lowest yield'))
} else{
    print('Another peanut line has the lowest yield')
}

[1] "Another peanut line has the lowest yield"


In [21]:
### Testing along all LINES which has the lowest yield

test <- min(peanuts$yield)

if (peanuts$yield[1]== test){
    print(paste(peanuts$lines[1],'has the lowest yield'))
} else if (peanuts$yield[2]== test){
    print(paste(peanuts$lines[2],'has the lowest yield'))
} else if (peanuts$yield[3]== test){
    print(paste(peanuts$lines[3],'has the lowest yield'))
} else {
    print(paste(peanuts$lines[4],'has the lowest yield'))
}

[1] "Emery has the lowest yield"


In [23]:
# FOR function can iterate along the range
for (i in 1:nrow(peanuts)){
    if (peanuts$yield[i]== test){
    print(paste(peanuts$lines[i],'has the lowest yield'))
    }
}

[1] "Emery has the lowest yield"


In [ ]:
# For Loops

# for (temprary_variable in object){
    #Execute some code
#}

In [27]:
vec <- c(1,2,3,4,5)

for (i in vec){
    print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [29]:
for (i in 1:3){
    print(i)
}

[1] 1
[1] 2
[1] 3


In [31]:
df<-women
df

height weight
1  58     115   
2  59     117   
3  60     120   
4  61     123   
5  62     126   
6  63     129   
7  64     132   
8  65     135   
9  66     139   
10 67     142   
11 68     146   
12 69     150   
13 70     154   
14 71     159   
15 72     164

In [33]:
for ( i in 1:length(df)){
    print(paste(sprintf("individual %s", i),"height = ",df$height[i],"and Weight = ",df$weight[i]))
}

[1] "individual 1 height =  58 and Weight =  115"
[1] "individual 2 height =  59 and Weight =  117"


In [35]:
for ( i in 1:nrow(df)){
    print(paste(sprintf("individual %s", i),"height = ",df$height[i],"and Weight = ",df$weight[i]))
}

[1] "individual 1 height =  58 and Weight =  115"
[1] "individual 2 height =  59 and Weight =  117"
[1] "individual 3 height =  60 and Weight =  120"
[1] "individual 4 height =  61 and Weight =  123"
[1] "individual 5 height =  62 and Weight =  126"
[1] "individual 6 height =  63 and Weight =  129"
[1] "individual 7 height =  64 and Weight =  132"
[1] "individual 8 height =  65 and Weight =  135"
[1] "individual 9 height =  66 and Weight =  139"
[1] "individual 10 height =  67 and Weight =  142"
[1] "individual 11 height =  68 and Weight =  146"
[1] "individual 12 height =  69 and Weight =  150"
[1] "individual 13 height =  70 and Weight =  154"
[1] "individual 14 height =  71 and Weight =  159"
[1] "individual 15 height =  72 and Weight =  164"


In [38]:
#NESTED FOR LOOPS

mat = matrix(1:25,nrow=5,byrow=F)
mat

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

In [40]:
for (row in 1:nrow(mat)){
    for (col in 1:ncol(mat)){
        print(paste("The element at row:",row,"and col:",col,'is',mat[row,col]))
    }
}

# NOTE THAT THE HIGHER ORDER LOOP STAYS TILL THE LOWER ORDER LOOP ITERATES COMPLETELY
# IN THIS CASE THE ROW NUMBER 1 REMAINS TILL ALL COLUMNS ITERATE ALONG ROW 1.

[1] "The element at row: 1 and col: 1 is 1"
[1] "The element at row: 1 and col: 2 is 6"
[1] "The element at row: 1 and col: 3 is 11"
[1] "The element at row: 1 and col: 4 is 16"
[1] "The element at row: 1 and col: 5 is 21"
[1] "The element at row: 2 and col: 1 is 2"
[1] "The element at row: 2 and col: 2 is 7"
[1] "The element at row: 2 and col: 3 is 12"
[1] "The element at row: 2 and col: 4 is 17"
[1] "The element at row: 2 and col: 5 is 22"
[1] "The element at row: 3 and col: 1 is 3"
[1] "The element at row: 3 and col: 2 is 8"
[1] "The element at row: 3 and col: 3 is 13"
[1] "The element at row: 3 and col: 4 is 18"
[1] "The element at row: 3 and col: 5 is 23"
[1] "The element at row: 4 and col: 1 is 4"
[1] "The element at row: 4 and col: 2 is 9"
[1] "The element at row: 4 and col: 3 is 14"
[1] "The element at row: 4 and col: 4 is 19"
[1] "The element at row: 4 and col: 5 is 24"
[1] "The element at row: 5 and col: 1 is 5"
[1] "The element at row: 5 and col: 2 is 10"
[1] "The element at

In [41]:
li <- list(vec,mat,df)

In [49]:
for (i in li){
    print(i)
}

[1] 1 2 3 4 5
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    6   11   16   21
[2,]    2    7   12   17   22
[3,]    3    8   13   18   23
[4,]    4    9   14   19   24
[5,]    5   10   15   20   25
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164


In [74]:
li[[2]][1:2,1:2]

[,1] [,2]
[1,] 1    6   
[2,] 2    7