In [2]:
# Dataframe about states
state.x77

Population Income Illiteracy Life Exp Murder HS Grad Frost
Alabama         3615      3624   2.1        69.05    15.1   41.3     20  
Alaska           365      6315   1.5        69.31    11.3   66.7    152  
Arizona         2212      4530   1.8        70.55     7.8   58.1     15  
Arkansas        2110      3378   1.9        70.66    10.1   39.9     65  
California     21198      5114   1.1        71.71    10.3   62.6     20  
Colorado        2541      4884   0.7        72.06     6.8   63.9    166  
Connecticut     3100      5348   1.1        72.48     3.1   56.0    139  
Delaware         579      4809   0.9        70.06     6.2   54.6    103  
Florida         8277      4815   1.3        70.66    10.7   52.6     11  
Georgia         4931      4091   2.0        68.54    13.9   40.6     60  
Hawaii           868      4963   1.9        73.60     6.2   61.9      0  
Idaho            813      4119   0.6        71.87     5.3   59.5    126  
Illinois       11197      5107   0.9        70.14    10.3   52.6    127  
Indiana         5313      4458   0.7        70.88     7.1   52.9    122  
Iowa            2861      4628   0.5        72.56     2.3   59.0    140  
Kansas          2280      4669   0.6        72.58     4.5   59.9    114  
Kentucky        3387      3712   1.6        70.10    10.6   38.5     95  
Louisiana       3806      3545   2.8        68.76    13.2   42.2     12  
Maine           1058      3694   0.7        70.39     2.7   54.7    161  
Maryland        4122      5299   0.9        70.22     8.5   52.3    101  
Massachusetts   5814      4755   1.1        71.83     3.3   58.5    103  
Michigan        9111      4751   0.9        70.63    11.1   52.8    125  
Minnesota       3921      4675   0.6        72.96     2.3   57.6    160  
Mississippi     2341      3098   2.4        68.09    12.5   41.0     50  
Missouri        4767      4254   0.8        70.69     9.3   48.8    108  
Montana          746      4347   0.6        70.56     5.0   59.2    155  
Nebraska        1544      4508   0.6        72.60     2.9   59.3    139  
Nevada           590      5149   0.5        69.03    11.5   65.2    188  
New Hampshire    812      4281   0.7        71.23     3.3   57.6    174  
New Jersey      7333      5237   1.1        70.93     5.2   52.5    115  
New Mexico      1144      3601   2.2        70.32     9.7   55.2    120  
New York       18076      4903   1.4        70.55    10.9   52.7     82  
North Carolina  5441      3875   1.8        69.21    11.1   38.5     80  
North Dakota     637      5087   0.8        72.78     1.4   50.3    186  
Ohio           10735      4561   0.8        70.82     7.4   53.2    124  
Oklahoma        2715      3983   1.1        71.42     6.4   51.6     82  
Oregon          2284      4660   0.6        72.13     4.2   60.0     44  
Pennsylvania   11860      4449   1.0        70.43     6.1   50.2    126  
Rhode Island     931      4558   1.3        71.90     2.4   46.4    127  
South Carolina  2816      3635   2.3        67.96    11.6   37.8     65  
South Dakota     681      4167   0.5        72.08     1.7   53.3    172  
Tennessee       4173      3821   1.7        70.11    11.0   41.8     70  
Texas          12237      4188   2.2        70.90    12.2   47.4     35  
Utah            1203      4022   0.6        72.90     4.5   67.3    137  
Vermont          472      3907   0.6        71.64     5.5   57.1    168  
Virginia        4981      4701   1.4        70.08     9.5   47.8     85  
Washington      3559      4864   0.6        71.72     4.3   63.5     32  
West Virginia   1799      3617   1.4        69.48     6.7   41.6    100  
Wisconsin       4589      4468   0.7        72.48     3.0   54.5    149  
Wyoming          376      4566   0.6        70.29     6.9   62.9    173  
               Area  
Alabama         50708
Alaska         566432
Arizona        113417
Arkansas        51945
California     156361
Colorado       103766
Connecticut      4862
Delaware         1982
Florida         54090
Georgia         58073

In [3]:
# US personal expense
USPersonalExpenditure

1940   1945   1950  1955 1960 
Food and Tobacco    22.200 44.500 59.60 73.2 86.80
Household Operation 10.500 15.500 29.00 36.5 46.20
Medical and Health   3.530  5.760  9.71 14.0 21.10
Personal Care        1.040  1.980  2.45  3.4  5.40
Private Education    0.341  0.974  1.80  2.6  3.64

In [4]:
# Women
women

height weight
1  58     115   
2  59     117   
3  60     120   
4  61     123   
5  62     126   
6  63     129   
7  64     132   
8  65     135   
9  66     139   
10 67     142   
11 68     146   
12 69     150   
13 70     154   
14 71     159   
15 72     164

In [5]:
# List of built-in R Dataframes
data()

In [6]:
# Quick variable assignment for shortcut
states <- state.x77

In [7]:
head(states)

Population Income Illiteracy Life Exp Murder HS Grad Frost Area  
Alabama     3615      3624   2.1        69.05    15.1   41.3     20    50708
Alaska       365      6315   1.5        69.31    11.3   66.7    152   566432
Arizona     2212      4530   1.8        70.55     7.8   58.1     15   113417
Arkansas    2110      3378   1.9        70.66    10.1   39.9     65    51945
California 21198      5114   1.1        71.71    10.3   62.6     20   156361
Colorado    2541      4884   0.7        72.06     6.8   63.9    166   103766

In [9]:
tail(states)

Population Income Illiteracy Life Exp Murder HS Grad Frost Area  
South Dakota    681      4167   0.5        72.08     1.7   53.3    172    75955
Tennessee      4173      3821   1.7        70.11    11.0   41.8     70    41328
Texas         12237      4188   2.2        70.90    12.2   47.4     35   262134
Utah           1203      4022   0.6        72.90     4.5   67.3    137    82096
Vermont         472      3907   0.6        71.64     5.5   57.1    168     9267
Virginia       4981      4701   1.4        70.08     9.5   47.8     85    39780
Washington     3559      4864   0.6        71.72     4.3   63.5     32    66570
West Virginia  1799      3617   1.4        69.48     6.7   41.6    100    24070
Wisconsin      4589      4468   0.7        72.48     3.0   54.5    149    54464
Wyoming         376      4566   0.6        70.29     6.9   62.9    173    97203

In [11]:
#Structure
str(states)

 num [1:50, 1:8] 3615 365 2212 2110 21198 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:50] "Alabama" "Alaska" "Arizona" "Arkansas" ...
  ..$ : chr [1:8] "Population" "Income" "Illiteracy" "Life Exp" ...


In [10]:
# Statistical summary of data
summary(states)

   Population        Income       Illiteracy       Life Exp    
 Min.   :  365   Min.   :3098   Min.   :0.500   Min.   :67.96  
 1st Qu.: 1080   1st Qu.:3993   1st Qu.:0.625   1st Qu.:70.12  
 Median : 2838   Median :4519   Median :0.950   Median :70.67  
 Mean   : 4246   Mean   :4436   Mean   :1.170   Mean   :70.88  
 3rd Qu.: 4968   3rd Qu.:4814   3rd Qu.:1.575   3rd Qu.:71.89  
 Max.   :21198   Max.   :6315   Max.   :2.800   Max.   :73.60  
     Murder          HS Grad          Frost             Area       
 Min.   : 1.400   Min.   :37.80   Min.   :  0.00   Min.   :  1049  
 1st Qu.: 4.350   1st Qu.:48.05   1st Qu.: 66.25   1st Qu.: 36985  
 Median : 6.850   Median :53.25   Median :114.50   Median : 54277  
 Mean   : 7.378   Mean   :53.11   Mean   :104.46   Mean   : 70736  
 3rd Qu.:10.675   3rd Qu.:59.15   3rd Qu.:139.75   3rd Qu.: 81162  
 Max.   :15.100   Max.   :67.30   Max.   :188.00   Max.   :566432  

In [12]:
# data.frame()
days <- c('Mon','Tue','Wed','Thu','Fri')
temp <- c(76.3, 89.2, 67.4, 91.2, 79.3)
rain <- c(T, F, T, F, T)


In [13]:
days

[1] "Mon" "Tue" "Wed" "Thu" "Fri"

In [14]:
df <- data.frame(days,temp,rain)

In [15]:
df

days temp rain 
1 Mon  76.3  TRUE
2 Tue  89.2 FALSE
3 Wed  67.4  TRUE
4 Thu  91.2 FALSE
5 Fri  79.3  TRUE

In [16]:
str(df)

'data.frame':	5 obs. of  3 variables:
 $ days: Factor w/ 5 levels "Fri","Mon","Thu",..: 2 4 5 3 1
 $ temp: num  76.3 89.2 67.4 91.2 79.3
 $ rain: logi  TRUE FALSE TRUE FALSE TRUE


In [19]:
# Get row and columns counts
nrow(df)
ncol(df)

[1] 5

[1] 3

In [20]:
# Get column names
colnames(df)
rownames(df)

[1] "days" "temp" "rain"

[1] "1" "2" "3" "4" "5"

In [21]:
# Indexing and Selection follow df [row,column]

#First df
df[1,]

days temp rain
1 Mon  76.3 TRUE

In [22]:
df[,1]

[1] Mon Tue Wed Thu Fri
Levels: Fri Mon Thu Tue Wed

In [24]:
# Grab Friday data
df[5,]

days temp rain
5 Fri  79.3 TRUE

In [26]:
df[,'rain']

[1]  TRUE FALSE  TRUE FALSE  TRUE

In [28]:
# First 5 rows for days and temps
df[1:5, c('days','temp')]

days temp
1 Mon  76.3
2 Tue  89.2
3 Wed  67.4
4 Thu  91.2
5 Fri  79.3

In [33]:
#EXTRA from indexing -> looking inside the column
df[df$days=="Fri",]

days temp rain
5 Fri  79.3 TRUE

In [34]:
str(df)

'data.frame':	5 obs. of  3 variables:
 $ days: Factor w/ 5 levels "Fri","Mon","Thu",..: 2 4 5 3 1
 $ temp: num  76.3 89.2 67.4 91.2 79.3
 $ rain: logi  TRUE FALSE TRUE FALSE TRUE


In [35]:
# dataframe$colname
df$rain

[1]  TRUE FALSE  TRUE FALSE  TRUE

In [36]:
df$days

[1] Mon Tue Wed Thu Fri
Levels: Fri Mon Thu Tue Wed

In [37]:
df['rain']

rain 
1  TRUE
2 FALSE
3  TRUE
4 FALSE
5  TRUE

In [38]:
### REFERENCE CELLS

In [42]:
# Creating a vector from a referenced cell
vec <- df[[5,2]]
vec

[1] 79.3

In [40]:
# Making a new Dataframe from df
newdf <- df[1:3, 1:2]
newdf

days temp
1 Mon  76.3
2 Tue  89.2
3 Wed  67.4

In [43]:
# Single brackets return the value with the data structure
df["rain"]

rain 
1  TRUE
2 FALSE
3  TRUE
4 FALSE
5  TRUE

In [48]:
# Double bracktes return just the value with no strucutre
df[['rain']]

[1]  TRUE FALSE  TRUE FALSE  TRUE

In [49]:
# Double bracktes is equivalent to the dollar sign $
df$rain

[1]  TRUE FALSE  TRUE FALSE  TRUE

In [50]:
# Making a new Dataframe from df
newdf <- df[1:3, 1:2]
newdf

days temp
1 Mon  76.3
2 Tue  89.2
3 Wed  67.4

In [51]:
#Changing the values of cells
df[[2, 'rain']] <- TRUE
df

days temp rain 
1 Mon  76.3  TRUE
2 Tue  89.2  TRUE
3 Wed  67.4  TRUE
4 Thu  91.2 FALSE
5 Fri  79.3  TRUE

In [52]:
#Create a new column
df

days temp rain 
1 Mon  76.3  TRUE
2 Tue  89.2  TRUE
3 Wed  67.4  TRUE
4 Thu  91.2 FALSE
5 Fri  79.3  TRUE

In [53]:
df$celcius <- (df$temp - 32) * 5/9
df

days temp rain  celcius 
1 Mon  76.3  TRUE 24.61111
2 Tue  89.2  TRUE 31.77778
3 Wed  67.4  TRUE 19.66667
4 Thu  91.2 FALSE 32.88889
5 Fri  79.3  TRUE 26.27778

In [54]:
df['over.80'] <- df['temp'] > 80
df

days temp rain  celcius  over.80
1 Mon  76.3  TRUE 24.61111 FALSE  
2 Tue  89.2  TRUE 31.77778  TRUE  
3 Wed  67.4  TRUE 19.66667 FALSE  
4 Thu  91.2 FALSE 32.88889  TRUE  
5 Fri  79.3  TRUE 26.27778 FALSE

In [55]:
# SUBSETTING

In [56]:
# Grabbing a subset of data where rain==TRUE
subset(df, subset= rain==TRUE)

days temp rain celcius  over.80
1 Mon  76.3 TRUE 24.61111 FALSE  
2 Tue  89.2 TRUE 31.77778  TRUE  
3 Wed  67.4 TRUE 19.66667 FALSE  
5 Fri  79.3 TRUE 26.27778 FALSE

In [57]:
# Grab a subset where temperature was greater than 80 degrees
subset(df, temp > 80)

days temp rain  celcius  over.80
2 Tue  89.2  TRUE 31.77778 TRUE   
4 Thu  91.2 FALSE 32.88889 TRUE

In [58]:
# Multi-conditional statements are done using & (and) and | (or)

In [60]:
df

days temp rain  celcius  over.80
1 Mon  76.3  TRUE 24.61111 FALSE  
2 Tue  89.2  TRUE 31.77778  TRUE  
3 Wed  67.4  TRUE 19.66667 FALSE  
4 Thu  91.2 FALSE 32.88889  TRUE  
5 Fri  79.3  TRUE 26.27778 FALSE

In [59]:
subset(df,days!='Wed' & temp<80 )

days temp rain celcius  over.80
1 Mon  76.3 TRUE 24.61111 FALSE  
5 Fri  79.3 TRUE 26.27778 FALSE

In [61]:
subset(df,days!='Wed' | temp<80 )

days temp rain  celcius  over.80
1 Mon  76.3  TRUE 24.61111 FALSE  
2 Tue  89.2  TRUE 31.77778  TRUE  
3 Wed  67.4  TRUE 19.66667 FALSE  
4 Thu  91.2 FALSE 32.88889  TRUE  
5 Fri  79.3  TRUE 26.27778 FALSE

In [96]:
# Same operation using the index command [row,col]
df[(df$days != 'Mon' & df$temp < 80),]

days temp rain celcius  over.80
3 Wed  67.4 TRUE 19.66667 FALSE  
5 Fri  79.3 TRUE 26.27778 FALSE

In [117]:
# Also works like this!!!
df[(df[['days']] != 'Wed' & df[['temp']] < 80),]

days temp rain celcius  over.80
1 Mon  76.3 TRUE 24.61111 FALSE  
5 Fri  79.3 TRUE 26.27778 FALSE

In [118]:
# Ordering R Dataframes

# order()

In [119]:
sorted.temp <- order(df$temp)

In [120]:
df[sorted.temp,]

days temp rain  celcius  over.80
3 Wed  67.4  TRUE 19.66667 FALSE  
1 Mon  76.3  TRUE 24.61111 FALSE  
5 Fri  79.3  TRUE 26.27778 FALSE  
2 Tue  89.2  TRUE 31.77778  TRUE  
4 Thu  91.2 FALSE 32.88889  TRUE

In [122]:
df[order(df[['temp']]),]

days temp rain  celcius  over.80
3 Wed  67.4  TRUE 19.66667 FALSE  
1 Mon  76.3  TRUE 24.61111 FALSE  
5 Fri  79.3  TRUE 26.27778 FALSE  
2 Tue  89.2  TRUE 31.77778  TRUE  
4 Thu  91.2 FALSE 32.88889  TRUE

In [123]:
# Use the other column reference technique to sort in descending order
desc.temp <- order(-df['temp'])

In [124]:
df[desc.temp,]

days temp rain  celcius  over.80
4 Thu  91.2 FALSE 32.88889  TRUE  
2 Tue  89.2  TRUE 31.77778  TRUE  
5 Fri  79.3  TRUE 26.27778 FALSE  
1 Mon  76.3  TRUE 24.61111 FALSE  
3 Wed  67.4  TRUE 19.66667 FALSE

In [1]:
# Vector of Integers
c1 <- 1:10

In [2]:
# Vector of Characters - Use letters to pull from the alphabet
c2 <- letters[1:10]

In [3]:
df <- data.frame(col.name.1 = c1, col.name.2 = c2)

In [4]:
df

col.name.1 col.name.2
1   1         a         
2   2         b         
3   3         c         
4   4         d         
5   5         e         
6   6         f         
7   7         g         
8   8         h         
9   9         i         
10 10         j

In [5]:
# Adding rows using rbind()
df2 <- data.frame(col.name.1=2000, col.name.2='new')
rbind(df, df2)

col.name.1 col.name.2
1     1       a         
2     2       b         
3     3       c         
4     4       d         
5     5       e         
6     6       f         
7     7       g         
8     8       h         
9     9       i         
10   10       j         
11 2000       new

In [6]:
# Adding columns
times.2 <- df$col.name.1 * 2
cbind(df, times.2)

col.name.1 col.name.2 times.2
1   1         a           2     
2   2         b           4     
3   3         c           6     
4   4         d           8     
5   5         e          10     
6   6         f          12     
7   7         g          14     
8   8         h          16     
9   9         i          18     
10 10         j          20

In [68]:
peanut.weight <- data.frame(
    name = I(c('Bailey','Bailey II','Wynne','Emery','Sullivan', 'Gregory')),
    weight = c(89.4, 92.3, 105.2, 103.1, 99.6, 89.1))
peanut.skins <- data.frame(
    name = I(c('Bailey','Bailey II','Wynne','Emery','Sullivan','Brantley')),
    skin = c('Tan', 'Tan', 'Pink', 'Pink', 'Tan', 'Red'))

In [69]:
peanut.weight

name      weight
1 Bailey     89.4 
2 Bailey II  92.3 
3 Wynne     105.2 
4 Emery     103.1 
5 Sullivan   99.6 
6 Gregory    89.1

In [70]:
peanut.skins

name      skin
1 Bailey    Tan 
2 Bailey II Tan 
3 Wynne     Pink
4 Emery     Pink
5 Sullivan  Tan 
6 Brantley  Red

In [71]:
merge(peanut.weight, peanut.skins, by.x = 'name', by.y = 'name')

name      weight skin
1 Bailey     89.4  Tan 
2 Bailey II  92.3  Tan 
3 Emery     103.1  Pink
4 Sullivan   99.6  Tan 
5 Wynne     105.2  Pink

In [72]:
peanuts <- merge(peanut.weight, peanut.skins, by.x = 'name', by.y = 'name', all = TRUE)
peanuts

name      weight skin
1 Bailey     89.4  Tan 
2 Bailey II  92.3  Tan 
3 Brantley     NA  Red 
4 Emery     103.1  Pink
5 Gregory    89.1  NA  
6 Sullivan   99.6  Tan 
7 Wynne     105.2  Pink

In [73]:
# Determine if there are missing data anywhere in peanuts

# any()
# is.na()

any(is.na(peanuts))

[1] TRUE

In [74]:
# Determine missing data points within columns
any(is.na(peanuts$skin))

[1] TRUE

In [75]:
any(is.na(peanuts$name))

[1] FALSE

In [93]:
# Delete selected missing data rows using '!' meaning 'NOT'
peanuts[!is.na(peanuts$weight),]

name      weight skin
1 Bailey     89.4  Tan 
2 Bailey II  92.3  Tan 
4 Emery     103.1  Pink
5 Gregory    89.1  NA  
6 Sullivan   99.6  Tan 
7 Wynne     105.2  Pink

In [94]:
# Replace the NA values with information


In [103]:
# Replace the NA values with information
peanuts[is.na(peanuts)] <- 90.0

Warning message in `[<-.factor`(`*tmp*`, thisvar, value = 90):
“invalid factor level, NA generated”

In [104]:
peanuts

name      weight skin
1 Bailey     89.4  Tan 
2 Bailey II  92.3  Tan 
3 Brantley   90.0  Red 
4 Emery     103.1  Pink
5 Gregory    89.1  NA  
6 Sullivan   99.6  Tan 
7 Wynne     105.2  Pink

In [105]:
# For selected columns
peanuts$skin[is.na(peanuts$skin)] <- 'Tan'
peanuts

name      weight skin
1 Bailey     89.4  Tan 
2 Bailey II  92.3  Tan 
3 Brantley   90.0  Red 
4 Emery     103.1  Pink
5 Gregory    89.1  Tan 
6 Sullivan   99.6  Tan 
7 Wynne     105.2  Pink

In [106]:
# Create a vector
v <- c(1,2,3,4,5)

# Create a matrix
m <- matrix(1:10, nrow = 2)

# Create a Dataframe
df <- women

In [107]:
v

[1] 1 2 3 4 5

In [108]:
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [109]:
df

height weight
1  58     115   
2  59     117   
3  60     120   
4  61     123   
5  62     126   
6  63     129   
7  64     132   
8  65     135   
9  66     139   
10 67     142   
11 68     146   
12 69     150   
13 70     154   
14 71     159   
15 72     164

In [110]:
li <- list(v, m, df)
li

[[1]]
[1] 1 2 3 4 5

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

In [119]:
li <- list(sample_vec = v, sample_mat = m, sample_df = df)
li

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

In [124]:
# Use brackets to select an object from the list using an index
li[1]

$sample_vec
[1] 1 2 3 4 5

In [125]:
# Use brackets to select an object by name
li['sample_vec']

$sample_vec
[1] 1 2 3 4 5

In [126]:
# Use double brackets to grab the elements from the index
li[['sample_vec']]

[1] 1 2 3 4 5

In [127]:
# Can use the '$' notation
li$sample_vec

[1] 1 2 3 4 5

In [128]:
# Use indexing to select elements within objects
li[['sample_vec']][1]

[1] 1

In [129]:
li[['sample_mat']]

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [130]:
li[['sample_mat']][1,]

[1] 1 3 5 7 9

In [131]:
li[['sample_mat']][1:2,1:2]

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [132]:
li[['sample_df']]['height']

height
1  58    
2  59    
3  60    
4  61    
5  62    
6  63    
7  64    
8  65    
9  66    
10 67    
11 68    
12 69    
13 70    
14 71    
15 72

In [135]:
# Doubling list
double_list <- c(li, li)
double_list

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

In [136]:
str(double_list)

List of 6
 $ sample_vec: num [1:5] 1 2 3 4 5
 $ sample_mat: int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ sample_df :'data.frame':	15 obs. of  2 variables:
  ..$ height: num [1:15] 58 59 60 61 62 63 64 65 66 67 ...
  ..$ weight: num [1:15] 115 117 120 123 126 129 132 135 139 142 ...
 $ sample_vec: num [1:5] 1 2 3 4 5
 $ sample_mat: int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ sample_df :'data.frame':	15 obs. of  2 variables:
  ..$ height: num [1:15] 58 59 60 61 62 63 64 65 66 67 ...
  ..$ weight: num [1:15] 115 117 120 123 126 129 132 135 139 142 ...


In [151]:
double_list[[3]][1:5,'height']

[1] 58 59 60 61 62