In [1]:
# R matrices

In [2]:
# Range of sequential numeric values
1:10

[1]  1  2  3  4  5  6  7  8  9 10

In [3]:
#Assign sequential numeric range to a vector
v<-1:10

In [4]:
# matrix() function
matrix(v)

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

In [5]:
matrix(v,nrow=2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [8]:
matrix(v,byrow=T,nrow=2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

In [9]:
matrix(1:12,byrow=T,nrow=4)

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [17]:
Lewiston <- c(12,14,18,13,17)
Rocky.Mount <- c(11,19,21,15,18)
Whiteville <- c(14,17,23,11,9)

In [21]:
weights<-c(Lewiston,Rocky.Mount,Whiteville);weights

[1] 12 14 18 13 17 11 19 21 15 18 14 17 23 11  9

In [22]:
weights.matrix<-matrix(weights,byrow=T,nrow=3);weights.matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 12   14   18   13   17  
[2,] 11   19   21   15   18  
[3,] 14   17   23   11    9

In [23]:
# Name rows = rownames(),columns = colnames()
days <- c("Mon","Tue","Wed",'Thu','Fri')
loc.names<-c('Lewiston','Rocky Mount','Whiteville')

In [24]:
days

[1] "Mon" "Tue" "Wed" "Thu" "Fri"

In [25]:
loc.names

[1] "Lewiston"    "Rocky Mount" "Whiteville"

In [26]:
colnames(weights.matrix)<-days
rownames(weights.matrix)<-loc.names

In [27]:
weights.matrix

Mon Tue Wed Thu Fri
Lewiston    12  14  18  13  17 
Rocky Mount 11  19  21  15  18 
Whiteville  14  17  23  11   9

In [31]:
mat <- matrix(1:50,byrow=T,nrow=5);mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [32]:
2*mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  2    4    6    8   10   12   14   16   18    20  
[2,] 22   24   26   28   30   32   34   36   38    40  
[3,] 42   44   46   48   50   52   54   56   58    60  
[4,] 62   64   66   68   70   72   74   76   78    80  
[5,] 82   84   86   88   90   92   94   96   98   100