In [3]:
# install a library/modules
import numpy as np #shortcut to call numpy with less characters. Python understands that np will refer to numpy

In [6]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [7]:
np.array(my_list)   # library.method()

array([1, 2, 3])

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]];my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
#Generating arrays in numpy

In [13]:
# arange()
np.arange(0,10) #--> do not include 10, in python the last value is the where it goes up to

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#Step by 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
# zeros()
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
# ones()
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
# linspace() -> linear spaced values

# Total of 3 numbers spaces evenly from 0 to 10
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [26]:
# Look up 10
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [27]:
# eye(diag) --> creates diagonals
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
# np.random() -> creating random values

# .rand follows a uniform ditribution
np.random.rand(10)

array([0.01733604, 0.14908134, 0.70897985, 0.82846208, 0.40111346,
       0.16687151, 0.76168525, 0.53076077, 0.64963743, 0.9084302 ])

In [31]:
np.random.rand(5,5)

array([[0.80809205, 0.17713895, 0.46279705, 0.3978533 , 0.43381411],
       [0.27799855, 0.19437969, 0.69026755, 0.24606383, 0.05161227],
       [0.17201624, 0.1527824 , 0.85102543, 0.59249647, 0.19437159],
       [0.50737605, 0.49808916, 0.07562915, 0.43670575, 0.70915265],
       [0.46826014, 0.34305406, 0.10802664, 0.87639842, 0.59949126]])

In [32]:
# standard normal distribution randn()

np.random.randn(10)

array([-0.3334489 , -1.02119756,  1.13874784,  0.39010232,  1.13637832,
        0.34452831,  0.28223851,  1.05695905, -0.10938342, -0.24017583])

In [33]:
np.random.randn(5,5)

array([[-0.33786279,  0.03383607, -0.24370192,  0.27446107, -1.89596746],
       [-0.29366005,  0.56228037, -0.42880296, -1.06933079,  0.04851573],
       [-1.45973254,  0.90883353,  1.44339658,  0.33889761, -0.26909478],
       [ 0.53003226, -0.35422971, -2.46098324,  2.14808074,  1.07047134],
       [-0.32105215, -0.43080598, -1.10741515, -0.60494995,  0.24477919]])

In [35]:
# random integers from low (includive) to high (exclusive) in a range
np.random.randint(1,100,10)  #(min,max,#values print)

array([94, 35, 67,  5, 80, 17, 73, 21, 13, 26])

In [38]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranarr

array([30, 38, 45, 16, 43, 11, 31,  7, 37, 10])

In [42]:
arr.reshape(5,5) #--> takes all 25 numbers and re-shape in a 5 by 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ranarr.max()

45

In [44]:
ranarr.argmax() #returns the position of the maximum number

2

In [45]:
ranarr

array([30, 38, 45, 16, 43, 11, 31,  7, 37, 10])

In [47]:
ranarr[2]

45

In [48]:
ranarr.min()

7

In [49]:
arr.shape

(25,)

In [50]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [51]:
arr.reshape(1,25).shape

(1, 25)

In [53]:
arr.reshape(25,1).shape

(25, 1)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
arr = np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
#converting to matrix.  --> necessary to perform matrices algebra
np.mat(arr)

matrix([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [58]:
arr.dtype

dtype('int64')

In [60]:
arr = np.arange(25)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
arr[8]

8

In [63]:
arr[1:5] # lower end included, upper end excluded

array([1, 2, 3, 4])

In [64]:
arr[0:5] = 100

In [65]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [69]:
arr = np.arange(25)

In [71]:
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [72]:
slice_arr[:] = 99

In [73]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [74]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [75]:
arr_copy = arr[0:6].copy()

In [77]:
arr_copy

array([99, 99, 99, 99, 99, 99])

In [79]:
arr2d = np.array(([5,10,15],[20,25,30],[35,40,45]));arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [80]:
#How to create the same matrix in another way?

In [83]:
np.arange(5,46,5).reshape(3,3)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [84]:
arr2d[1]

array([20, 25, 30])

In [86]:
arr2d[0]

array([ 5, 10, 15])

In [87]:
# array [row,col]; array [row][col]
arr2d [1,0]

20

In [90]:
arr2d[:2,:2] # grab eveything up to row and column 2 (column and row are excluded)

array([[ 5, 10],
       [20, 25]])

In [91]:
arr2d[2]

array([35, 40, 45])

In [92]:
arr2d[:,2] #last column

array([15, 30, 45])

In [93]:
arr2d = np.arange(1,101).reshape(10,10)
arr2d

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [94]:
arr2d[[0,2,4,6,8]] #calls rows

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [95]:
arr2d[[1,7,3,5,2]] # calls rows out of order in any order

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [96]:
arr2d[:,[1,2,3,4]] # grab columns

array([[ 2,  3,  4,  5],
       [12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45],
       [52, 53, 54, 55],
       [62, 63, 64, 65],
       [72, 73, 74, 75],
       [82, 83, 84, 85],
       [92, 93, 94, 95]])

In [98]:
arr2d[:,[5,1,6,2,3]]

array([[ 6,  2,  7,  3,  4],
       [16, 12, 17, 13, 14],
       [26, 22, 27, 23, 24],
       [36, 32, 37, 33, 34],
       [46, 42, 47, 43, 44],
       [56, 52, 57, 53, 54],
       [66, 62, 67, 63, 64],
       [76, 72, 77, 73, 74],
       [86, 82, 87, 83, 84],
       [96, 92, 97, 93, 94]])

In [99]:
#Diagonal
arr2d[[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9]]

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [102]:
plus30=arr2d > 30 ; plus30

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [103]:
arr2d[plus30]

array([ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100])

In [104]:
np.max(arr2d)

100

In [106]:
np.log(arr2d)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
        1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
        2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
        3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738],
       [3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
        3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945],
       [3.71357207, 3.73766962, 3.76120012, 3.78418963, 3.80666249,
        3.8286414 , 3.8501476 , 3.87120101, 3.8918203 , 3.91202301],
       [3.93182563, 3.95124372, 3.97029191, 3.98898405, 4.00733319,
        4.02535169, 4.04305127, 4.06044301, 4.07753744, 4.09434456],
       [4.11087386, 4.12713439, 4.14313473, 4.15888308, 4.17438727,
        4.18965474, 4.20469262, 4.21950771, 4.2341065 , 4.24849524],
       [4.26267988, 4.27666612, 4.2904594

In [107]:
# matrix algebra

A = np.arange(1,5).reshape(2,2)

In [109]:
A

array([[1, 2],
       [3, 4]])

In [110]:
A*A # Element by element

array([[ 1,  4],
       [ 9, 16]])

In [111]:
# converting to matrix
a = np.mat(A)

In [113]:
a*a

matrix([[ 7, 10],
        [15, 22]])

In [114]:
a.T

matrix([[1, 3],
        [2, 4]])

In [116]:
a.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])